version: 2.1

# -------------------------------------------------------------------------------------
# Commands
# -------------------------------------------------------------------------------------

commands:

  py_3_7_setup:
    description: "Install and switch to Python 3.7.5; also install pip and pytest."
    steps:
      - run:
          name: "Setup Python v3.7.5 environment"
          command: |
            cd /opt/circleci/.pyenv && git pull && cd -
            pyenv install -s 3.7.5
            pyenv global 3.7.5
            pyenv local 3.7.5
            pyenv versions
            echo "In venv: $(pyenv local) - $(python -V), $(pip -V)"
            sudo "$(which python)" -m pip install --upgrade pip
            sudo "$(which python)" -m pip install pytest
