# text dependent hey portal; trained only on Hey Portal clips
SYSTEM:
  CUDNN_BENCHMARK: True
INPUT:
  TRIM_MS: 1100
TRAIN:
  LOSS: "cross_entropy"
  CLIP_LENGTH: 100
  BATCH_SIZE: 256
  MAX_EPOCH: 15
  OPTIM:
    SOLVER: adam
    MAX_LR: 7e-3
    WEIGHT_DECAY: 0.4

  SPEC_AUG:
    F: 8
    PROB: 0.25
    NUM_FREQ_MASK: 2

MODEL:
  ARCH: default
  TRUNK_CH_OUT: 128
  EMBEDDING_SIZE: 256
  TIME_POOLING_METHOD: attn
  ARC_MARGIN:
    M: 0.01
    M_END: 0.3
    S: 16.0
  EMBEDDING_DROPOUT: 0.4

DATASETS:
  TRAIN: ("hp12dftrim_ti_train_all",)
  TEST: ("combined_eval",)
TEST:
  ENROLLMENT_CLIP_LENGTH: 100
  PROBE_CLIP_LENGTH: 100
  ENROLLMENT_CLIP_COUNTS: (4,)
  SESSION_COUNT: 1200
  PROBE_COUNT_PER_ENROLLEE: 1
