name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run pytest
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3  
    
      - name: Set up Python
        uses: actions/setup-python@v4  
        with:
          python-version: '3.8.10' 

      - name: Cache Python dependencies
        uses: actions/cache@v3  
        with:
          path: ~/.cache/pip  
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}  
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  
          pip install -r requirements.txt  
          
      - name: Run pytest with coverage
        run: pytest -ra --cov=. --cov-report term-missing 
